version: 2.1

orbs:
  ansible: circleci/ansible@0.1.6

jobs:
  deploy-job:
    executor: ansible/default
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install Ansible
          command: sudo apt-get update && sudo apt-get install -y ansible
      - run:
          name: Run Ansible playbook
          command: ansible-playbook -i inventory.yml --private-key=$HOME/.ssh/aws servers.yml

  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Build and push Docker image
          command: |
            docker build -t nodeapp .
            docker tag nodeapp $username/nodeapp:$CIRCLE_BUILD_NUM
            docker login -u $username -p $password
            docker push $username/nodeapp:$CIRCLE_BUILD_NUM
            ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/aws ubuntu@ec2-35-88-72-141.us-west-2.compute.amazonaws.com "
            docker run -d -p 3000:3000 --name test $username/nodeapp:$CIRCLE_BUILD_NUM"

workflows:
  build-deploy:
    jobs:
      - deploy-job
      - build:
          requires:
            - deploy-job
