version: 2.1

jobs:
  deploy-job:
    docker:
      - image: circleci/python:3.9

    steps:
      - checkout
      - run:
          name: Install Ansible
          command: sudo pip3 install ansible
      - run:
          name: Run Ansible playbook
          command: ansible-playbook -i inventory.yml --private-key=$HOME/.ssh/aws servers.yml

  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Build and push Docker image
          command: |
            docker build -t nodeapp .
            docker tag nodeapp $username/nodeapp:$CIRCLE_BUILD_NUM
            docker login -u $username -p $password
            docker push $username/nodeapp:$CIRCLE_BUILD_NUM
            ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/aws ubuntu@ec2-54-184-243-185.us-west-2.compute.amazonaws.com "
            docker run -d -p 3000:3000 --name test $username/nodeapp:$CIRCLE_BUILD_NUM"

workflows:
  build-deploy:
    jobs:
      - deploy-job
      - build:
          requires:
            - deploy-job
