version: 2
jobs:
  deploy:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "c3:37:69:80:da:ac:ac:bf:b1:55:29:37:ca:c8:18:68"
            
  build-and-deploy:
    docker:
      - image: aseelibrahimm/docker-ansible:lts
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            docker build -t nodeapp .
            docker tag nodeapp $username/nodeapp:$CIRCLE_BUILD_NUM
            docker login -u $username -p $password
            docker push $username/nodeapp:$CIRCLE_BUILD_NUM
      - run:
          name: Run Ansible playbook
          command: ansible-playbook -i inventory.yml --private-key=$HOME/.ssh/aws --extra-vars "username=${username} CIRCLE_BUILD_NUM=${CIRCLE_BUILD_NUM}" playbook.yml

workflows:
  version: 2
  build-and-deploy-workflow:
    jobs:
      - build-and-deploy
